FROM python:3.10-slim

WORKDIR /opt/app

# ✅ add this block
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc g++ make \
    libglib2.0-0 \
    libgl1 \
    libxcb1 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "app.main", "--config", "config/pds_netra_config.yaml", "--device", "cpu"]
