FROM python:3.10-slim

WORKDIR /opt/app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "app.main", "--config", "config/pds_netra_config.yaml", "--device", "cpu"]