"""
Pydantic schemas for alerts in PDS Netra backend.

Alerts are generated by the central rule engine. The ``AlertOut``
schema includes summary information and a count of linked events.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel


class AlertOut(BaseModel):
    id: int
    godown_id: str
    camera_id: Optional[str]
    alert_type: str
    severity_final: str
    start_time: datetime
    end_time: Optional[datetime]
    status: str
    summary: Optional[str]
    zone_id: Optional[str]
    count_events: int
    linked_event_ids: List[int]

    class Config:
        orm_mode = True
