"""
ORM model for face match events generated by edge watchlist detection.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import String, DateTime, Boolean, Float, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column

from . import Base


class FaceMatchEvent(Base):
    __tablename__ = "face_match_events"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)  # event_id
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    godown_id: Mapped[str] = mapped_column(String(64), index=True)
    camera_id: Mapped[str] = mapped_column(String(64), index=True)
    stream_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    match_score: Mapped[float] = mapped_column(Float)
    is_blacklisted: Mapped[bool] = mapped_column(Boolean, default=False)
    blacklist_person_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("watchlist_persons.id"), nullable=True)
    snapshot_url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    storage_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    correlation_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    raw_payload: Mapped[dict] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
